export const MBTI_TRAITS_CONFIG = [
  {
    title: '감정',
    leftLabel: '불안형',
    rightLabel: '평온형',
    keys: { left: 'anxietyScore', right: 'stabilityScore' },
    leftDescription: '과도하게 걱정하며 위험에 민감해요.',
    rightDescription: '감정기복이 적어요.',
    leftDetails: [
      '미래의 손실이나 불확실성에 과도하게 반응해요.',
      '작은 변동에도 스트레스를 느끼며 안전을 최우선으로 둬요.',
    ],
    rightDetails: ['감정 기복이 적고 상황 변화에 비교적 담담해요.', '금융 의사결정에서도 감정 개입이 적은 편이에요.'],
  },
  {
    title: '자기조절',
    leftLabel: '충동형',
    rightLabel: '계획형',
    keys: { left: 'impulseScore', right: 'planningScore' },
    leftDescription: '순간적 생각에 따라 소비를 결정해요.',
    rightDescription: '소비계획을 철저히 세우며 지켜요.',
    leftDetails: ['순간의 감정이나 생각에 따라 소비를 결정해요.', '계획보다 즉각적인 만족을 우선시하는 경향이 있어요.'],
    rightDetails: ['사전에 소비 기준과 예산을 세우고 이를 지키려 해요.', '지출에 명확한 이유와 구조가 존재해요.'],
  },
  {
    title: '위험신호',
    leftLabel: '공격형',
    rightLabel: '안전형',
    keys: { left: 'aggressiveScore', right: 'conservativeScore' },
    leftDescription: '고수익, 위험성있는 상품을 선호해요.',
    rightDescription: '손실을 피하고 원금을 보호하길 원해요.',
    leftDetails: ['고수익을 기대할 수 있다면 위험도 감수해요.', '변동성이 큰 상품에도 비교적 열린 태도를 보여요.'],
    rightDetails: ['손실 가능성을 크게 경계해요.', '원금 보존과 안정성을 가장 중요한 기준으로 삼아요.'],
  },
  {
    title: '의사결정',
    leftLabel: '회피-소비중심형',
    rightLabel: '합리-목표중심형',
    keys: { left: 'avoidanceScore', right: 'rationalScore' },
    leftDescription: '결정을 미루며 현재의 만족을 우선시해요.',
    rightDescription: '논리적 판단. 소비는 목표를 위한 수단으로 기능해요.',
    leftDetails: ['결정을 미루며 현재의 안정과 만족을 유지하려 해요.', '선택으로 인한 책임이나 후회를 부담스러워해요.'],
    rightDetails: ['감정보다 근거와 계산을 바탕으로 판단해요.', '소비와 투자는 목표 달성을 위한 수단으로 기능해요.'],
  },
];
