/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Typography variants
    'text-title-1',
    'text-title-2',
    'text-title-3',
    'text-headline-1',
    'text-headline-2',
    'text-headline-3',
    'text-body-1',
    'text-body-1-reading',
    'text-body-2',
    'text-body-3',
    'text-caption-1',
    'text-caption-2',
    // Font weights
    'font-bold',
    'font-semi-bold',
    'font-medium',
    'font-regular',
  ],
  theme: {
    extend: {
      colors: {
        // Neutrals
        neutral: {
          0: 'var(--color-neutral-0)',
          10: 'var(--color-neutral-10)',
          20: 'var(--color-neutral-20)',
          30: 'var(--color-neutral-30)',
          40: 'var(--color-neutral-40)',
          50: 'var(--color-neutral-50)',
          60: 'var(--color-neutral-60)',
          70: 'var(--color-neutral-70)',
          80: 'var(--color-neutral-80)',
          90: 'var(--color-neutral-90)',
          100: 'var(--color-neutral-100)',
        },
        // Base Colors
        white: 'var(--color-white)',
        black: 'var(--color-black)',
        bg: 'var(--color-bg)',
        // Primary Colors (pri -> primary로 개선)
        primary: {
          DEFAULT: 'var(--color-pri-normal)',
          normal: 'var(--color-pri-normal)',
          strong: 'var(--color-pri-strong)',
          heavy: 'var(--color-pri-heavy)',
          light: 'var(--color-pri-light)',
        },

        // Bank Colors
        bank: {
          plus: 'var(--color-bank-plus)',
          kb: 'var(--color-bank-kb)',
          citi: 'var(--color-bank-citi)',
          kbank: 'var(--color-bank-kbank)',
          saemaul: 'var(--color-bank-saemaul)',
          ibk: 'var(--color-bank-ibk)',
          gwanju_jeonbuk: 'var(--color-bank-gwanju_jeonbuk)'
        },
        // Atomic Colors
        atomic: {
          common: {
            0: 'var(--color-atomic-common-0)',
            100: 'var(--color-atomic-common-100)',
          },
          red: {
            0: 'var(--color-atomic-red-0)',
            10: 'var(--color-atomic-red-10)',
            20: 'var(--color-atomic-red-20)',
            30: 'var(--color-atomic-red-30)',
            40: 'var(--color-atomic-red-40)',
            50: 'var(--color-atomic-red-50)',
            60: 'var(--color-atomic-red-60)',
            70: 'var(--color-atomic-red-70)',
            80: 'var(--color-atomic-red-80)',
            90: 'var(--color-atomic-red-90)',
            95: 'var(--color-atomic-red-95)',
            99: 'var(--color-atomic-red-99)',
            100: 'var(--color-atomic-red-100)',
          },
          'red-orange': {
            0: 'var(--color-atomic-red-orange-0)',
            10: 'var(--color-atomic-red-orange-10)',
            20: 'var(--color-atomic-red-orange-20)',
            30: 'var(--color-atomic-red-orange-30)',
            40: 'var(--color-atomic-red-orange-40)',
            48: 'var(--color-atomic-red-orange-48)',
            50: 'var(--color-atomic-red-orange-50)',
            60: 'var(--color-atomic-red-orange-60)',
            70: 'var(--color-atomic-red-orange-70)',
            80: 'var(--color-atomic-red-orange-80)',
            90: 'var(--color-atomic-red-orange-90)',
            95: 'var(--color-atomic-red-orange-95)',
            99: 'var(--color-atomic-red-orange-99)',
            100: 'var(--color-atomic-red-orange-100)',
          },
          orange: {
            0: 'var(--color-atomic-orange-0)',
            10: 'var(--color-atomic-orange-10)',
            20: 'var(--color-atomic-orange-20)',
            30: 'var(--color-atomic-orange-30)',
            39: 'var(--color-atomic-orange-39)',
            40: 'var(--color-atomic-orange-40)',
            50: 'var(--color-atomic-orange-50)',
            60: 'var(--color-atomic-orange-60)',
            70: 'var(--color-atomic-orange-70)',
            80: 'var(--color-atomic-orange-80)',
            90: 'var(--color-atomic-orange-90)',
            95: 'var(--color-atomic-orange-95)',
            99: 'var(--color-atomic-orange-99)',
            100: 'var(--color-atomic-orange-100)',
          },
          lime: {
            0: 'var(--color-atomic-lime-0)',
            10: 'var(--color-atomic-lime-10)',
            20: 'var(--color-atomic-lime-20)',
            30: 'var(--color-atomic-lime-30)',
            37: 'var(--color-atomic-lime-37)',
            40: 'var(--color-atomic-lime-40)',
            50: 'var(--color-atomic-lime-50)',
            60: 'var(--color-atomic-lime-60)',
            70: 'var(--color-atomic-lime-70)',
            80: 'var(--color-atomic-lime-80)',
            90: 'var(--color-atomic-lime-90)',
            95: 'var(--color-atomic-lime-95)',
            99: 'var(--color-atomic-lime-99)',
            100: 'var(--color-atomic-lime-100)',
          },
          green: {
            0: 'var(--color-atomic-green-0)',
            10: 'var(--color-atomic-green-10)',
            20: 'var(--color-atomic-green-20)',
            30: 'var(--color-atomic-green-30)',
            40: 'var(--color-atomic-green-40)',
            50: 'var(--color-atomic-green-50)',
            60: 'var(--color-atomic-green-60)',
            70: 'var(--color-atomic-green-70)',
            80: 'var(--color-atomic-green-80)',
            90: 'var(--color-atomic-green-90)',
            95: 'var(--color-atomic-green-95)',
            99: 'var(--color-atomic-green-99)',
            100: 'var(--color-atomic-green-100)',
          },
          cyan: {
            0: 'var(--color-atomic-cyan-0)',
            10: 'var(--color-atomic-cyan-10)',
            20: 'var(--color-atomic-cyan-20)',
            30: 'var(--color-atomic-cyan-30)',
            40: 'var(--color-atomic-cyan-40)',
            50: 'var(--color-atomic-cyan-50)',
            60: 'var(--color-atomic-cyan-60)',
            70: 'var(--color-atomic-cyan-70)',
            80: 'var(--color-atomic-cyan-80)',
            90: 'var(--color-atomic-cyan-90)',
            95: 'var(--color-atomic-cyan-95)',
            99: 'var(--color-atomic-cyan-99)',
            100: 'var(--color-atomic-cyan-100)',
          },
          'light-blue': {
            0: 'var(--color-atomic-light-blue-0)',
            10: 'var(--color-atomic-light-blue-10)',
            20: 'var(--color-atomic-light-blue-20)',
            30: 'var(--color-atomic-light-blue-30)',
            40: 'var(--color-atomic-light-blue-40)',
            50: 'var(--color-atomic-light-blue-50)',
            60: 'var(--color-atomic-light-blue-60)',
            70: 'var(--color-atomic-light-blue-70)',
            80: 'var(--color-atomic-light-blue-80)',
            90: 'var(--color-atomic-light-blue-90)',
            95: 'var(--color-atomic-light-blue-95)',
            99: 'var(--color-atomic-light-blue-99)',
            100: 'var(--color-atomic-light-blue-100)',
          },
          blue: {
            0: 'var(--color-atomic-blue-0)',
            10: 'var(--color-atomic-blue-10)',
            20: 'var(--color-atomic-blue-20)',
            30: 'var(--color-atomic-blue-30)',
            40: 'var(--color-atomic-blue-40)',
            45: 'var(--color-atomic-blue-45)',
            50: 'var(--color-atomic-blue-50)',
            55: 'var(--color-atomic-blue-55)',
            60: 'var(--color-atomic-blue-60)',
            65: 'var(--color-atomic-blue-65)',
            70: 'var(--color-atomic-blue-70)',
            80: 'var(--color-atomic-blue-80)',
            90: 'var(--color-atomic-blue-90)',
            95: 'var(--color-atomic-blue-95)',
            99: 'var(--color-atomic-blue-99)',
            100: 'var(--color-atomic-blue-100)',
          },
          violet: {
            0: 'var(--color-atomic-violet-0)',
            10: 'var(--color-atomic-violet-10)',
            20: 'var(--color-atomic-violet-20)',
            30: 'var(--color-atomic-violet-30)',
            40: 'var(--color-atomic-violet-40)',
            45: 'var(--color-atomic-violet-45)',
            50: 'var(--color-atomic-violet-50)',
            60: 'var(--color-atomic-violet-60)',
            70: 'var(--color-atomic-violet-70)',
            80: 'var(--color-atomic-violet-80)',
            90: 'var(--color-atomic-violet-90)',
            95: 'var(--color-atomic-violet-95)',
            99: 'var(--color-atomic-violet-99)',
            100: 'var(--color-atomic-violet-100)',
          },
          purple: {
            0: 'var(--color-atomic-purple-0)',
            10: 'var(--color-atomic-purple-10)',
            20: 'var(--color-atomic-purple-20)',
            30: 'var(--color-atomic-purple-30)',
            40: 'var(--color-atomic-purple-40)',
            50: 'var(--color-atomic-purple-50)',
            60: 'var(--color-atomic-purple-60)',
            70: 'var(--color-atomic-purple-70)',
            80: 'var(--color-atomic-purple-80)',
            90: 'var(--color-atomic-purple-90)',
            95: 'var(--color-atomic-purple-95)',
            99: 'var(--color-atomic-purple-99)',
            100: 'var(--color-atomic-purple-100)',
          },
          pink: {
            0: 'var(--color-atomic-pink-0)',
            10: 'var(--color-atomic-pink-10)',
            20: 'var(--color-atomic-pink-20)',
            30: 'var(--color-atomic-pink-30)',
            40: 'var(--color-atomic-pink-40)',
            46: 'var(--color-atomic-pink-46)',
            50: 'var(--color-atomic-pink-50)',
            60: 'var(--color-atomic-pink-60)',
            70: 'var(--color-atomic-pink-70)',
            80: 'var(--color-atomic-pink-80)',
            90: 'var(--color-atomic-pink-90)',
            95: 'var(--color-atomic-pink-95)',
            99: 'var(--color-atomic-pink-99)',
            100: 'var(--color-atomic-pink-100)',
          },
          yellow: {
            10: 'var(--color-atomic-yellow-10)',
            20: 'var(--color-atomic-yellow-20)',
            30: 'var(--color-atomic-yellow-30)',
            40: 'var(--color-atomic-yellow-40)',
            50: 'var(--color-atomic-yellow-50)',
            60: 'var(--color-atomic-yellow-60)',
            70: 'var(--color-atomic-yellow-70)',
            80: 'var(--color-atomic-yellow-80)',
            90: 'var(--color-atomic-yellow-90)',
            95: 'var(--color-atomic-yellow-95)',
          },
        },
        // Text Colors
        text: {
          title: 'var(--color-text-title)',
          body: 'var(--color-text-body)',
          'sub-body': 'var(--color-text-sub-body)',
          disabled: 'var(--color-text-disabled)',
        },
        // Status Colors
        status: {
          error: 'var(--color-status-error)',
          abled: 'var(--color-status-abled)',
        },
        // Line Colors
        line: {
          900: 'var(--color-line-900)',
        },
      },
      fontFamily: {
        pretendard: ['var(--font-family-pretendard)', 'sans-serif'],
        preahvihear: ['var(--font-family-preahvihear)', 'sans-serif'],
      },
      fontSize: {
        // 숫자 기반 (기존 호환성 유지)
        0: ['var(--font-size-0)', { lineHeight: 'var(--line-height-30)' }],
        1: ['var(--font-size-1)', { lineHeight: 'var(--line-height-30)' }],
        2: ['var(--font-size-2)', { lineHeight: 'var(--line-height-27)' }],
        3: ['var(--font-size-3)', { lineHeight: 'var(--line-height-24)' }],
        4: ['var(--font-size-4)', { lineHeight: 'var(--line-height-18)' }],
        5: ['var(--font-size-5)', { lineHeight: 'var(--line-height-15)' }],
        6: ['var(--font-size-6)', { lineHeight: 'var(--line-height-12)' }],
        7: ['var(--font-size-7)', { lineHeight: 'var(--line-height-9)' }],
        8: ['var(--font-size-8)', { lineHeight: 'var(--line-height-6)' }],
        9: ['var(--font-size-9)', { lineHeight: 'var(--line-height-3)' }],
        10: ['var(--font-size-10)', { lineHeight: 'var(--line-height-0)' }],
        // 의미있는 이름 (권장)
        'title-1': ['var(--font-size-10)', { lineHeight: 'var(--line-height-0)', letterSpacing: 'var(--letter-spacing-0)' }],
        'title-2': ['var(--font-size-9)', { lineHeight: 'var(--line-height-3)', letterSpacing: 'var(--letter-spacing-0)' }],
        'title-3': ['var(--font-size-8)', { lineHeight: 'var(--line-height-6)', letterSpacing: 'var(--letter-spacing-0)' }],
        'headline-1': ['var(--font-size-7)', { lineHeight: 'var(--line-height-9)', letterSpacing: 'var(--letter-spacing-0)' }],
        'headline-2': ['var(--font-size-6)', { lineHeight: 'var(--line-height-12)', letterSpacing: 'var(--letter-spacing-0)' }],
        'headline-3': ['var(--font-size-5)', { lineHeight: 'var(--line-height-15)', letterSpacing: 'var(--letter-spacing-0)' }],
        'body-1': ['var(--font-size-4)', { lineHeight: 'var(--line-height-18)', letterSpacing: 'var(--letter-spacing-0)' }],
        'body-1-reading': ['var(--font-size-4)', { lineHeight: 'var(--line-height-15)', letterSpacing: 'var(--letter-spacing-0)' }],
        'body-2': ['var(--font-size-3)', { lineHeight: 'var(--line-height-24)', letterSpacing: 'var(--letter-spacing-0)' }],
        'body-3': ['var(--font-size-2)', { lineHeight: 'var(--line-height-27)', letterSpacing: 'var(--letter-spacing-0)' }],
        'caption-1': ['var(--font-size-1)', { lineHeight: 'var(--line-height-30)', letterSpacing: 'var(--letter-spacing-0)' }],
        'caption-2': ['var(--font-size-0)', { lineHeight: 'var(--line-height-30)', letterSpacing: 'var(--letter-spacing-0)' }],
      },
      fontWeight: {
        bold: 'var(--font-weight-bold)',
        'semi-bold': 'var(--font-weight-semi-bold)',
        medium: 'var(--font-weight-medium)',
        regular: 'var(--font-weight-regular)',
      },
      letterSpacing: {
        0: 'var(--letter-spacing-0)',
        1: 'var(--letter-spacing-1)',
      },
      lineHeight: {
        0: 'var(--line-height-0)',
        1: 'var(--line-height-1)',
        2: 'var(--line-height-2)',
        3: 'var(--line-height-3)',
        4: 'var(--line-height-4)',
        5: 'var(--line-height-5)',
        6: 'var(--line-height-6)',
        7: 'var(--line-height-7)',
        8: 'var(--line-height-8)',
        9: 'var(--line-height-9)',
        10: 'var(--line-height-10)',
        11: 'var(--line-height-11)',
        12: 'var(--line-height-12)',
        13: 'var(--line-height-13)',
        14: 'var(--line-height-14)',
        15: 'var(--line-height-15)',
        16: 'var(--line-height-16)',
        17: 'var(--line-height-17)',
        18: 'var(--line-height-18)',
        19: 'var(--line-height-19)',
        20: 'var(--line-height-20)',
        21: 'var(--line-height-21)',
        22: 'var(--line-height-22)',
        23: 'var(--line-height-23)',
        24: 'var(--line-height-24)',
        25: 'var(--line-height-25)',
        26: 'var(--line-height-26)',
        27: 'var(--line-height-27)',
        28: 'var(--line-height-28)',
        29: 'var(--line-height-29)',
        30: 'var(--line-height-30)',
        31: 'var(--line-height-31)',
        32: 'var(--line-height-32)',
        33: 'var(--line-height-33)',
        34: 'var(--line-height-34)',
        35: 'var(--line-height-35)',
      },
    },
  },
  plugins: [],
}
